import Head from "next/head";
import Filters from "../components/demo/Filters";
import Dashboard from './Dashboard';
import { useSession, signIn, signOut } from "next-auth/react"


export default function Home() {
  
  
    // const { data: session } = useSession()
    //   if(session) {
    //     return <>
    //       Signed in as {session.user.email} <br/>
    //       <button onClick={() => signOut()}>Sign out</button>
    //     </>
    //   }
    //   return <>
    //     Not signed in <br/>
    //     <button onClick={() => signIn()}>Sign in</button>
    //   </>



  return (



    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta charset="utf-8" />
      </Head>

      <main className="container">
        {/* <p className="text-4xl text-blue-600">heading</p> */}
        {/* <Filters /> */}
          <Dashboard/>
      </main>
    </div>
  );
}
